### ISSUE TITLE
About OGB submission

### ISSUE THREAD

**Issue by weihua916** [skepsun/HSAGN_with_SLE#1]
Thanks for your leaderboard submission. To be qualified for the leaderboard, we require writing a specialized technical report that describes your approach (e.g., how you exactly combined all the components). Please also provide the exact command, step-by-step instruction to reproduce your best result: see this [README](https://github.com/PaddlePaddle/PGL/tree/main/ogb_examples/nodeproppred/unimp) for an example. Please reply here once all these are done.

Thank you!

**Comment by weihua916** [comment]
You can either write a short technical report or update your SLE arXiv paper to describe how you exactly combined SLE and NARS.

**Comment by skepsun** [comment]
Thanks for your kind reminders!
I agree that a detailed report should be included. I will soon update
README and my SLE arxiv paper.



Weihua Hu ***@***.***> 于2021年7月1日周四 上午6:38写道：

**Comment by skepsun** [comment]
README has been updated.

**Comment by weihua916** [comment]
Looks great! Let me know once the paper is updated.

**Comment by skepsun** [comment]
The paper has been updated. Check the part of NARS_SAGN+SLE in Appendices.

**Comment by weihua916** [comment]
Great, updated the leaderboard!
